apiVersion: apps/v1
kind: Deployment
metadata:
  name: turees-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: turees-web
  template:
    metadata:
      labels:
        app: turees-web
    spec:
      containers:
        - name: turees-web
          image: buynaa24/turees-web:latest
          ports:
            - containerPort: 3000
          env:
            - name: URL
              value: "http://192.168.0.108:8081"
            - name: SOCKET
              value: "http://192.168.0.108:8081"
            - name: HTTP_URL
              value: "http://192.168.0.108:8081"
